"""
app/agents/disclaimers.py — Tax/compliance disclaimer injection.
"""
from __future__ import annotations

import re

from pydantic import BaseModel

TAX_COMPLIANCE_KEYWORDS = re.compile(
    r"\b(tax.loss|capital.gains|rmd|required.minimum"
    r"|wash.sale|estate.planning|gift.tax|irs|1099"
    r"|k-1|tax.bracket|charitable|qualified.dividend"
    r"|amt|alternative.minimum|compliance|regulatory"
    r"|fiduciary|suitability)\b",
    re.IGNORECASE,
)

DISCLAIMER_TEXT = (
    "This analysis is generated by an AI assistant "
    "and is intended for informational purposes only. "
    "It does not constitute tax, legal, or compliance "
    "advice. Advisors should verify all figures against "
    "authoritative sources and consult qualified "
    "professionals before acting on any recommendation."
)


class Disclaimer(BaseModel):
    required: bool
    text: str | None = None
    triggered_by: list[str] = []


def check_disclaimer(content: str) -> Disclaimer:
    """Check if content requires a disclaimer."""
    matches = TAX_COMPLIANCE_KEYWORDS.findall(content)
    if matches:
        return Disclaimer(
            required=True,
            text=DISCLAIMER_TEXT,
            triggered_by=list(set(matches)),
        )
    return Disclaimer(required=False)
